export const DELETE_ERROR = 'DELETE_ERROR';

export const FETCH_MEALS_START = 'FETCH_MEALS_START';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAIL = 'FETCH_MEALS_FAIL';

export const FETCH_ONE_MEAL_SUCCESS = 'FETCH_ONE_MEAL_SUCCESS';
export const FETCH_ONE_MEAL_FAIL = 'FETCH_ONE_MEAL_FAIL';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const ADD_MEAL_INTO_VIEW_LIST = 'ADD_MEAL_INTO_VIEW_LIST';
export const ADD_MEAL_INTO_VIEW_LIST_START = 'ADD_MEAL_INTO_VIEW_LIST_START';
export const ADD_MEAL_INTO_VIEW_LIST_SUCCESS = 'ADD_MEAL_INTO_VIEW_LIST_SUCCESS';
export const ADD_MEAL_INTO_VIEW_LIST_FAIL = 'ADD_MEAL_INTO_VIEW_LIST_FAIL';

export const DELETE_MEAL_INTO_VIEW_LIST_SUCCESS = 'DELETE_MEAL_INTO_VIEW_LIST_SUCCESS';

export const ADD_NEW_MEAL_SUCCESS = 'ADD_NEW_MEAL_SUCCESS';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';

export const FETCH_METHOD = 'FETCH_METHOD';
export const FETCH_METHOD_START = 'FETCH_METHOD_START';
export const FETCH_METHOD_SUCCESS = 'FETCH_METHOD_SUCCESS';
export const EDIT_METHOD = 'EDIT_METHOD';
export const DELETE_METHOD = 'DELETE_METHOD';